#ifndef __DECK_H__
#define __DECK_H__
#include "cocos2d.h"

enum cardName { KNIGHT, SQUIRE, LONGBOWMAN, SPEARMAN, SORCERER_APPRENTICE, MILITIAN, GOBLIN, PYROMANCERR, DIREWOLF, ALPHAWOLF, WOLF, WOLF_RIDER, VIKING, THIEF, TREBUCHET, 
	SORCERER, MAGE, WIZZARD, MEDIC, PRIEST, SUMMONER, PHALAX, MERCENARY, TACTICIAN, FIRST_AID, PLAGUE, FIREBALL, COMMAND_PROMOTE, COMMAND_SHIELD, COMMAND_SWORD, 
	COMMAND_VOLLEY, RATS, BLESSING, CHOSEN_ONE, EARTHQUAKE  };




#endif